#!/bin/bash

export PS1="\[$(tput setaf 1)\]\[$(tput bold)\]\t\[$(tput sgr0)\] \[$(tput setaf 6)\]\[$(tput bold)\]\u\[$(tput sgr0)\]\[$(tput setaf 5)\]\[$(tput bold)\]@\[$(tput setaf 7)\]\[$(tput bold)\]\h:\[$(tput sgr0)\]\[$(tput setaf 4)\]\[$(tput bold)\]\w $ \[$(tput sgr0)\]"

alias la="ls -A"
alias lh="ls -lah"
alias l="ls"
alias ll="ls -la"

# Handy Shortcuts
alias bash="$SHELL"
alias grep="grep --color=auto"
alias ..="cd .."

# Tools
alias p='particle'
alias py='python'

#Mac OS Only
if [ "$(uname -s)" == "Darwin" ];
then
  alias ls="ls -G"
  alias htop='sudo htop'
  alias atom='open -a Atom'
  alias chrome='open -a Google\ Chrome'
  alias new="open -a 'Terminal' ."
  alias ip='ipconfig getifaddr en0'
fi

# Git Shortcuts
alias pull="git pull"
alias check="git checkout"

function update()
{
  cd "$(pwd)"
  git add -A
  #git commit -S -m "$1 at $(date +"%H:%M") of $(date +"%Y-%m-%d")" # Replace the line below with this one for GPG signed commits
  git commit -m "$1 at $(date +"%H:%M") of $(date +"%Y-%m-%d")"
  git push -u origin $(git rev-parse --abbrev-ref HEAD)
}

function pull-all()
{
  CWD="$PWD"

  for OUTPUT in $(ls -1 "$CWD")
  do
    if [ -d "$CWD/$OUTPUT/.git" ]; # Only do git pull if it is a repository
    then
      cd "$CWD/$OUTPUT"
      blue_echo "Pulling $OUTPUT..."
      git pull
      echo
    fi
  done
  cd "$CWD"
}

alias skip-ci="update '[skip ci]'"

source "/usr/local/share/particle-cli.completion"
[ -f /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion
source /usr/local/etc/bash_completion.d/po

alias npm-install="sudo npm install -g --unsafe-perm"
